ci: step summary another test

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -40,6 +40,17 @@ jobs:
         fi
         echo "## Coverage summary:" >> $GITHUB_STEP_SUMMARY
         echo "$COVERAGE" | tail -n +2 >> $GITHUB_STEP_SUMMARY
+    - name: Coverage summary
+      id: coverage2
+      run: |
+        {
+        echo "## Coverage summary:"
+        npm run show-coverage
+        if [ $? -ne 0 ]; then
+          echo "Failed to retrieve coverage data."
+        fi
+        } >> $GITHUB_STEP_SUMMARY
+        
     # - name: Upload coverage reports to Codecov
     #   uses: codecov/codecov-action@v4.0.1
     #   with:
