ci: coverage again

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -28,12 +28,15 @@ jobs:
         cache: "npm"
         registry-url: "https://registry.npmjs.org"
     - run: npm ci
-    - run: npm test
-    - run: npm run coverage
+    - run: npm run test-coverage
     - name: Coverage summary
       id: coverage
       run: |
-        COVERAGE="$(npm run --silent show-coverage)"
+        COVERAGE="$(npm run show-coverage)"
+        if [ $? -ne 0 ]; then
+          echo "Error: Failed to retrieve coverage data."
+          exit 1
+        fi
         echo "$COVERAGE" | tail -n +2 >> $GITHUB_STEP_SUMMARY
     # - name: Upload coverage reports to Codecov
     #   uses: codecov/codecov-action@v4.0.1
